spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testH2/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace

server:
  port: 525