spring:
  # h2 설정
  h2:
    console:
      enabled: true
  # datasource 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/H2/poSeat;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # spl 보기
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  web:
#    resources:
#      static-locations: classpath:/resource/static/**
#####
logging:
  level:
    org.hibernate.type: trace
#####
server:
  port: 525